/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2026 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stm32f407xx.h>
#include<stm32f4xx.h>
#ifndef BV

#define BV(n) (1<<(n))
#endif
#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void) {
	RCC->AHB1ENR |= BV(3);
	GPIOD->MODER |= (BV(24) | BV(26) | BV(28) | BV(30));
	GPIOD->MODER &= ~(BV(25) | BV(27) | BV(29) | BV(31));
	GPIOD->OTYPER &= ~(BV(12) | BV(13) | BV(14) | BV(15));
	GPIOD->OSPEEDR &= ~(BV(24) | BV(26) | BV(28) | BV(30) | BV(25) | BV(27)
			| BV(29) | BV(31));
	GPIOD->PUPDR &= ~(BV(24) | BV(26) | BV(28) | BV(30) | BV(25) | BV(27)
			| BV(29) | BV(31));
	while (1) {
		GPIOD->ODR |= BV(12);
		DelayMs(500);
		GPIOD->ODR |= BV(13);
		DelayMs(500);
		GPIOD->ODR |= BV(14);
		DelayMs(500);
		GPIOD->ODR |= BV(15);
		DelayMs(500);
		GPIOD->ODR &= ~(BV(15));
		DelayMs(500);
		GPIOD->ODR &= ~(BV(14));
		DelayMs(500);
		GPIOD->ODR &= ~(BV(13));
		DelayMs(500);
		GPIOD->ODR &= ~(BV(12));
		DelayMs(500);

	}

}
